version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "project1/apprunner"
    AWS_ACCOUNT_ID: "048970710401"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - export IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .
      - docker tag $IMAGE_URI $IMAGE_URI:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $IMAGE_URI:latest
      - echo Build complete
